server:
  port: 2001

spring:
  application:
    name: seata-order-service # 微服务名称
  cloud:
    alibaba:
      seata:
        # 自定义事务组名称需要与seata/conf目录下的file.conf的service模块vgroup_mapping.my_test_tx_group对应
        tx-service-group: zzp_tx_group
    nacos:
      discovery:
        # 配置Nacos 注册中心
        server-addr: 127.0.0.1:8848
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
    url: jdbc:mysql://localhost:3306/seata_order?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: "root"
    password: "123456"

feign:
  hystrix:
    enabled: false

logging:
  level:
    io:
      seata: info

mybatis:
  mapperLocations: classpath:mapper/*.xml







