server:
  port: 7001 # 端口号

#spring:
#  application:
#    name: cloud-eureka-service # 项目名称

eureka:
  instance:
    hostname: localhost #eureka服务端的实例名字
#    instance-id: eureka7001 # 服务名称设置
#    prefer-ip-address: true # 访问路径可以显示ip地址
    allow-redirects: false # 是否向注册中心注册本服务：true为是。注册中心不需要将自己注册进去
    fetch-registry: false # false表示自己是注册中心，职责是维护服务实例，并不需要去检索服务
    service-url:
#      设置与eureka server交互的地址查询服务和注册服务都需要依赖这个地址,多个时用逗号隔开
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      #设置与eureka server交互的地址查询服务和注册服务都需要依赖这个地址
#      defaultZone: http://eureka7002.com:7002/eureka/
      defaultZone: http://eureka7001.com:7001/eureka/
#  server:
#    enable-self-preservation: false # 禁用自我保护模式
#    eviction-interval-timer-in-ms: 2000 # 2秒

